######## 회원가입1
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "username":"dnsielf",
  "email":"test2@naver.com",
  "password":"password123"
}


######## 로그인1
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "username":"dnsielf",
  "password":"password123"
}

######## 검색
POST http://localhost:8080/api/search
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkbnNpZWxmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYzMTE4OTk2fQ.HBwrdG7F2viC39_5MzNqdarDSSRkpbac73e-okIfVOQ
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjM3MjE5OTZ9.TQkkriJq3Y3s0gQPkg0y8i_riNDOeS2zPe7azKTsuVk
Content-Type: application/json

{
  "searchTitle": "경제"
}


######## post 작성
POST http://localhost:8080/api/auth/post
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkbnNpZWxmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYzMTE5ODYzfQ.QHhm4wMXjOF9Riu13m_R7vFMOnHidAabKtEAvwyOCJc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjM3MjI4NjN9.Xs3fc8AgHceHnXvT-9e7iEanWi8Yeh3GygzepouStDg
Content-Type: application/json

{
  "title": "책제목2",
  "username": "유저네임2",
  "content": "책 상세 내용2",
  "imageUrl": "url",
  "bookPage": 124,
  "star": 2,
  "readStart": "2022-10-2",
  "readEnd": "2022-11-2"
}


######## 모든 포스트 조회
GET http://localhost:8080/api/auth/post
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkbnNpZWxmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYzMTE5ODYzfQ.QHhm4wMXjOF9Riu13m_R7vFMOnHidAabKtEAvwyOCJc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjM3MjI4NjN9.Xs3fc8AgHceHnXvT-9e7iEanWi8Yeh3GygzepouStDg


######## 상세 포스트 조회
GET http://localhost:8080/api/auth/post/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkbnNpZWxmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYzMTE5ODYzfQ.QHhm4wMXjOF9Riu13m_R7vFMOnHidAabKtEAvwyOCJc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjM3MjI4NjN9.Xs3fc8AgHceHnXvT-9e7iEanWi8Yeh3GygzepouStDg


######## 포스트 삭제
DELETE http://localhost:8080/api/auth/post/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkbnNpZWxmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYzMTE5ODYzfQ.QHhm4wMXjOF9Riu13m_R7vFMOnHidAabKtEAvwyOCJc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjM3MjI4NjN9.Xs3fc8AgHceHnXvT-9e7iEanWi8Yeh3GygzepouStDg


######## post 수정
PUT http://localhost:8080/api/auth/post/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkbnNpZWxmIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjYzMTE5ODYzfQ.QHhm4wMXjOF9Riu13m_R7vFMOnHidAabKtEAvwyOCJc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjM3MjI4NjN9.Xs3fc8AgHceHnXvT-9e7iEanWi8Yeh3GygzepouStDg
Content-Type: application/json

{
  "title": "책제목3 수정",
  "star": 3,
  "readStart": "2022-10-3",
  "readEnd": "2022-11-4"
}

